/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/EliteM.glb 
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-forgotten-knight-d14eb14d83bd4e7ba7cbe443d76a10fd
Title: ⛨ The Forgotten Knight ⛨
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/EliteM.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0.248, 1.783, 0.363]} rotation={[2.443, -1.393, -0.88]} scale={0.496}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.roses_mat} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.roses_mat} />
      </group>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.cloak_mat} skeleton={nodes.Object_10.skeleton} />
      <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.center_armor_mat} skeleton={nodes.Object_12.skeleton} />
      <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.center_armor_mat} skeleton={nodes.Object_14.skeleton} />
      <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.eye_plug_mat} skeleton={nodes.Object_16.skeleton} />
      <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.top_armor_mat} skeleton={nodes.Object_18.skeleton} />
      <skinnedMesh geometry={nodes.Object_20.geometry} material={materials.top_armor_mat} skeleton={nodes.Object_20.skeleton} />
      <skinnedMesh geometry={nodes.Object_22.geometry} material={materials.bottom_armor_mat} skeleton={nodes.Object_22.skeleton} />
      <skinnedMesh geometry={nodes.Object_24.geometry} material={materials.center_armor_mat} skeleton={nodes.Object_24.skeleton} />
      <skinnedMesh geometry={nodes.Object_25.geometry} material={materials.details_mat} skeleton={nodes.Object_25.skeleton} />
      <skinnedMesh geometry={nodes.Object_27.geometry} material={materials.center_armor_mat} skeleton={nodes.Object_27.skeleton} />
      <skinnedMesh geometry={nodes.Object_28.geometry} material={materials.details_mat} skeleton={nodes.Object_28.skeleton} />
      <skinnedMesh geometry={nodes.Object_29.geometry} material={materials.top_armor_mat} skeleton={nodes.Object_29.skeleton} />
      <skinnedMesh geometry={nodes.Object_31.geometry} material={materials.details_mat} skeleton={nodes.Object_31.skeleton} />
      <mesh geometry={nodes.Object_103.geometry} material={materials.sword_mat} position={[0, 1.844, 0.392]} />
    </group>
  )
}

useGLTF.preload('/EliteM.glb')
