/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/EliteF.glb 
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/silksong-hornet-fanart-57d431b977c841ef8c117af82f109890
Title: Silksong || Hornet Fanart
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/EliteF.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[-0.044, -0.069, -0.045]} rotation={[0.12, -0.064, -0.086]}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.cloak_mat} skeleton={nodes.Object_7.skeleton} />
        <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.hornet_mat} skeleton={nodes.Object_9.skeleton} />
        <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.details_mat} skeleton={nodes.Object_11.skeleton} />
      </group>
      <mesh geometry={nodes.Object_77.geometry} material={materials['details_mat.001']} position={[-0.423, 0.928, 0.315]} rotation={[0.235, -0.573, 1.985]} scale={0.877} />
      <mesh geometry={nodes.Object_79.geometry} material={materials.thread_mat} position={[0.039, 0.883, 1.062]} />
    </group>
  )
}

useGLTF.preload('/EliteF.glb')
