/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useMemo } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = useRef()

  const { scene, animations } = useGLTF('/FinalG.glb')

  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  const { actions, names } = useAnimations(animations, group)

  // 🔥 PLAY ANIMATION
  useEffect(() => {
    if (!actions || names.length === 0) {
      console.warn("❌ No animations found")
      return
    }

    console.log("✅ Animations:", names)

    const action = actions[names[0]]
    action.reset().fadeIn(0.5).play()

    return () => action.fadeOut(0.5)
  }, [actions, names])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="main_reg">
          <primitive object={nodes.Root} />

          <group name="Body">
            <skinnedMesh geometry={nodes['Body_(merged)'].geometry} material={materials['N00_000_00_Body_00_SKIN (Instance)']} skeleton={nodes['Body_(merged)'].skeleton} />
            <skinnedMesh geometry={nodes['Body_(merged)_1'].geometry} material={materials['N00_000_00_HairBack_00_HAIR (Instance)']} skeleton={nodes['Body_(merged)_1'].skeleton} />
            <skinnedMesh geometry={nodes['Body_(merged)_2'].geometry} material={materials['Accessory_RabbitEar_01_CLOTH (Instance)']} skeleton={nodes['Body_(merged)_2'].skeleton} />
            <skinnedMesh geometry={nodes['Body_(merged)_3'].geometry} material={materials['Accessory_RabbitTail_01_CLOTH (Instance)']} skeleton={nodes['Body_(merged)_3'].skeleton} />
            <skinnedMesh geometry={nodes['Body_(merged)_4'].geometry} material={materials['N00_001_01_Shoes_01_CLOTH (Instance)']} skeleton={nodes['Body_(merged)_4'].skeleton} />
            <skinnedMesh geometry={nodes['Body_(merged)_5'].geometry} material={materials['N00_007_01_Tops_01_CLOTH (Instance)']} skeleton={nodes['Body_(merged)_5'].skeleton} />
            <skinnedMesh geometry={nodes['Body_(merged)_6'].geometry} material={materials['N00_001_03_Bottoms_01_CLOTH (Instance)']} skeleton={nodes['Body_(merged)_6'].skeleton} />
          </group>

          <skinnedMesh geometry={nodes.Hair.geometry} material={materials['N00_000_Hair_00_HAIR (Instance)']} skeleton={nodes.Hair.skeleton} />

          <group name="Face">
            <skinnedMesh geometry={nodes['Face_(merged)(Clone)'].geometry} material={materials['N00_000_00_FaceMouth_00_FACE (Instance)']} skeleton={nodes['Face_(merged)(Clone)'].skeleton} morphTargetDictionary={nodes['Face_(merged)(Clone)'].morphTargetDictionary} morphTargetInfluences={nodes['Face_(merged)(Clone)'].morphTargetInfluences} />
            <skinnedMesh geometry={nodes['Face_(merged)(Clone)_1'].geometry} material={materials['N00_000_00_EyeIris_00_EYE (Instance)']} skeleton={nodes['Face_(merged)(Clone)_1'].skeleton} morphTargetDictionary={nodes['Face_(merged)(Clone)_1'].morphTargetDictionary} morphTargetInfluences={nodes['Face_(merged)(Clone)_1'].morphTargetInfluences} />
            <skinnedMesh geometry={nodes['Face_(merged)(Clone)_2'].geometry} material={materials['N00_000_00_EyeHighlight_00_EYE (Instance)']} skeleton={nodes['Face_(merged)(Clone)_2'].skeleton} morphTargetDictionary={nodes['Face_(merged)(Clone)_2'].morphTargetDictionary} morphTargetInfluences={nodes['Face_(merged)(Clone)_2'].morphTargetInfluences} />
            <skinnedMesh geometry={nodes['Face_(merged)(Clone)_3'].geometry} material={materials['N00_000_00_Face_00_SKIN (Instance)']} skeleton={nodes['Face_(merged)(Clone)_3'].skeleton} morphTargetDictionary={nodes['Face_(merged)(Clone)_3'].morphTargetDictionary} morphTargetInfluences={nodes['Face_(merged)(Clone)_3'].morphTargetInfluences} />
            <skinnedMesh geometry={nodes['Face_(merged)(Clone)_4'].geometry} material={materials['N00_000_00_EyeWhite_00_EYE (Instance)']} skeleton={nodes['Face_(merged)(Clone)_4'].skeleton} morphTargetDictionary={nodes['Face_(merged)(Clone)_4'].morphTargetDictionary} morphTargetInfluences={nodes['Face_(merged)(Clone)_4'].morphTargetInfluences} />
            <skinnedMesh geometry={nodes['Face_(merged)(Clone)_5'].geometry} material={materials['N00_000_00_FaceBrow_00_FACE (Instance)']} skeleton={nodes['Face_(merged)(Clone)_5'].skeleton} morphTargetDictionary={nodes['Face_(merged)(Clone)_5'].morphTargetDictionary} morphTargetInfluences={nodes['Face_(merged)(Clone)_5'].morphTargetInfluences} />
            <skinnedMesh geometry={nodes['Face_(merged)(Clone)_6'].geometry} material={materials['N00_000_00_FaceEyeline_00_FACE (Instance)']} skeleton={nodes['Face_(merged)(Clone)_6'].skeleton} morphTargetDictionary={nodes['Face_(merged)(Clone)_6'].morphTargetDictionary} morphTargetInfluences={nodes['Face_(merged)(Clone)_6'].morphTargetInfluences} />
          </group>

        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/FinalG.glb')