/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/HotF.glb 
Author: golden4445etetet (https://sketchfab.com/golden4445etetet)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drake-balls-girl-android-2edb96937e57403ba01178c299ffdd37
Title: drake balls girl, android
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/HotF.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Mesh_0_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Mesh_0_Material001_0_1.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Mesh_0_Material001_0_2.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Mesh_0_Material001_0_3.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Mesh_0_Material001_0_4.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Mesh_0_Material001_0_5.geometry} material={materials['Material.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/HotF.glb')
