/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Solog.glb --transform 
Files: public/Solog.glb [0.13KB] > D:\Projects\Power_Up\Frontend\Solog-transformed.glb [0.13KB] (0%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Solog-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  )
}

useGLTF.preload('/Solog-transformed.glb')
